version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: peugeot_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - peugeot
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: peugeot_web
    restart: unless-stopped
    ports:
      - "8002:80"
      - "5173:5173"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - peugeot

  db:
    image: mysql:8.0
    container_name: peugeot_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: laravel
    ports:
      - "33062:3306"
    volumes:
      - peugeot_mysql_data:/var/lib/mysql
    networks:
      - peugeot

networks:
  peugeot:
    driver: bridge

volumes:
  peugeot_mysql_data:
